Add missing commas
../../../../../../kernel/xiaomi/beryllium/drivers/staging/qcacld-3.0/core/cds/src/cds_regdomain.c:284:43: error: suspicious concatenation of string literals in an array initialization; did you mean to separate the elements with a comma? [-Werror,-Wstring-concatenation]
        {CTRY_TURKS_AND_CAICOS, FCC3_WORLD, "TC" "TURKS AND CAICOS"},
                                                 ^
                                                ,
../../../../../../kernel/xiaomi/beryllium/drivers/staging/qcacld-3.0/core/cds/src/cds_regdomain.c:284:38: note: place parentheses around the string literal to silence warning
        {CTRY_TURKS_AND_CAICOS, FCC3_WORLD, "TC" "TURKS AND CAICOS"},
                                            ^
../../../../../../kernel/xiaomi/beryllium/drivers/staging/qcacld-3.0/core/cds/src/cds_regdomain.c:296:45: error: suspicious concatenation of string literals in an array initialization; did you mean to separate the elements with a comma? [-Werror,-Wstring-concatenation]
        {CTRY_WALLIS_AND_FUTUNA, ETSI1_WORLD, "WF" "WALLIS"},
                                                   ^
                                                  ,
../../../../../../kernel/xiaomi/beryllium/drivers/staging/qcacld-3.0/core/cds/src/cds_regdomain.c:296:40: note: place parentheses around the string literal to silence warning
        {CTRY_WALLIS_AND_FUTUNA, ETSI1_WORLD, "WF" "WALLIS"},
                                              ^
2 errors generated.